395 reduce complexity measure in twopoint class (#396)
* Refactoring: add initialize_sources
* Add docs for initialize_sources
* Refactoring: add handle_ccl_kind
* Refactoring: add type annotation
* Address pylint complaints
* Add McCabe complexity check to flake8 runs
* Turn TwoPoint.handle_ccl_kind to top-level method
* Refactoring: add method set_window_function
* ell_or_theta and stat arrays must be same length
* Make rarely-used args in TwoPoint initializer keyword-only
* Refactor: remove some redundancy
* Further breaking up of large temporary method
* Adding guard clause to theory window function
* Introduce TracerNames dataclass
* Add more testing for TwoPoint
* Make pre-commit-check safe to run as a script

---------

Co-authored-by: Matt Kwiecien <mattkwiecien@gmail.com>

diff --git a/pre-commit-check b/pre-commit-check
--- a/pre-commit-check
+++ b/pre-commit-check
@@ -1,16 +1,47 @@
 #!/usr/bin/env bash -x
 
-black firecrown/ examples/ tests/
+if black firecrown/ examples/ tests/; then
+  echo "black ok"
+else
+  echo "black failed"
+  exit 1
+fi
 
-flake8 firecrown/ examples/ tests/
 
-pylint firecrown
+if flake8 firecrown/ examples/ tests/; then
+  echo "flake8 ok"
+else
+  echo "flake8 failed"
+  exit 1
+fi
+  
+if pylint firecrown; then
+  echo "pylint ok for firecrown"
+else
+  echo "pylint failed for firecrown"
+  exit 1
+fi
 
-pylint --rcfile firecrown/models/pylintrc firecrown/models
+if pylint --rcfile firecrown/models/pylintrc firecrown/models; then
+  echo "pylint ok for firecrown.models"
+else
+  echo "pylint failed for firecrown.models"
+  exit 1
+fi
 
-pylint --rcfile tests/pylintrc tests
+if pylint --rcfile tests/pylintrc tests; then
+  echo "pylint ok for tests"
+else
+  echo "pylint failed for tests"
+  exit 1
+fi
 
-PERL5LIB= parallel ::: "mypy -p firecrown" "mypy -p tests" "mypy -p examples"
+if mypy -p firecrown -p examples -p tests; then
+  echo "mypy ok"
+else
+  echo "mypy failed"
+  exit 1
+fi
 
 python -m pytest --runslow -vv --integration tests
 
